use_frameworks!

platform :ios, '10.0'

target 'SFModuleApp_Example' do
  pod 'SFModuleApp', :path => '../'

  target 'SFModuleApp_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
