//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let entitlements = entitlements()

  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "English"
  }

  /// This `_R.image` struct is generated, and contains static references to 220 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Beethoven`.
    var beethoven: RswiftResources.ImageResource { .init(name: "Beethoven", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Cart_Add`.
    var cart_Add: RswiftResources.ImageResource { .init(name: "Cart_Add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `DanielWu.jpg`.
    var danielWuJpg: RswiftResources.ImageResource { .init(name: "DanielWu.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `DanielWuFace`.
    var danielWuFace: RswiftResources.ImageResource { .init(name: "DanielWuFace", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Dilraba.gif`.
    var dilrabaGif: RswiftResources.ImageResource { .init(name: "Dilraba.gif", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Download`.
    var download: RswiftResources.ImageResource { .init(name: "Download", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `EFQRCoder`.
    var efqrCoder: RswiftResources.ImageResource { .init(name: "EFQRCoder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `EyreFree`.
    var eyreFree: RswiftResources.ImageResource { .init(name: "EyreFree", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Gem.gif`.
    var gemGif: RswiftResources.ImageResource { .init(name: "Gem.gif", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Generator`.
    var generator: RswiftResources.ImageResource { .init(name: "Generator", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Girl1.jpg`.
    var girl1Jpg: RswiftResources.ImageResource { .init(name: "Girl1.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Girl2.jpg`.
    var girl2Jpg: RswiftResources.ImageResource { .init(name: "Girl2.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Girl3.jpg`.
    var girl3Jpg: RswiftResources.ImageResource { .init(name: "Girl3.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Girl4.jpg`.
    var girl4Jpg: RswiftResources.ImageResource { .init(name: "Girl4.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Girl5.jpg`.
    var girl5Jpg: RswiftResources.ImageResource { .init(name: "Girl5.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Girl6.jpg`.
    var girl6Jpg: RswiftResources.ImageResource { .init(name: "Girl6.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Girl7.jpg`.
    var girl7Jpg: RswiftResources.ImageResource { .init(name: "Girl7.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Girl8.jpg`.
    var girl8Jpg: RswiftResources.ImageResource { .init(name: "Girl8.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `GitHub`.
    var gitHub: RswiftResources.ImageResource { .init(name: "GitHub", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Heart`.
    var heart: RswiftResources.ImageResource { .init(name: "Heart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Jobs`.
    var jobs: RswiftResources.ImageResource { .init(name: "Jobs", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Kobe.jpg`.
    var kobeJpg: RswiftResources.ImageResource { .init(name: "Kobe.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `LPD`.
    var lpD: RswiftResources.ImageResource { .init(name: "LPD", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Miku`.
    var miku: RswiftResources.ImageResource { .init(name: "Miku", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Pikachu`.
    var pikachu: RswiftResources.ImageResource { .init(name: "Pikachu", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Plus`.
    var plus: RswiftResources.ImageResource { .init(name: "Plus", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `PopMenu_Logo`.
    var popMenu_Logo: RswiftResources.ImageResource { .init(name: "PopMenu_Logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Recognizer`.
    var recognizer: RswiftResources.ImageResource { .init(name: "Recognizer", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Settings_Icon`.
    var settings_Icon: RswiftResources.ImageResource { .init(name: "Settings_Icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Swift`.
    var swift: RswiftResources.ImageResource { .init(name: "Swift", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Trash`.
    var trash: RswiftResources.ImageResource { .init(name: "Trash", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WWF`.
    var wwF: RswiftResources.ImageResource { .init(name: "WWF", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Wille`.
    var wille: RswiftResources.ImageResource { .init(name: "Wille", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `appicon_1024`.
    var appicon_1024: RswiftResources.ImageResource { .init(name: "appicon_1024", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_120`.
    var appicon_120: RswiftResources.ImageResource { .init(name: "appicon_120", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_152`.
    var appicon_152: RswiftResources.ImageResource { .init(name: "appicon_152", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_167`.
    var appicon_167: RswiftResources.ImageResource { .init(name: "appicon_167", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_180`.
    var appicon_180: RswiftResources.ImageResource { .init(name: "appicon_180", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_20`.
    var appicon_20: RswiftResources.ImageResource { .init(name: "appicon_20", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_29`.
    var appicon_29: RswiftResources.ImageResource { .init(name: "appicon_29", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_40`.
    var appicon_40: RswiftResources.ImageResource { .init(name: "appicon_40", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_58`.
    var appicon_58: RswiftResources.ImageResource { .init(name: "appicon_58", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_60`.
    var appicon_60: RswiftResources.ImageResource { .init(name: "appicon_60", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_76`.
    var appicon_76: RswiftResources.ImageResource { .init(name: "appicon_76", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_80`.
    var appicon_80: RswiftResources.ImageResource { .init(name: "appicon_80", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `appicon_87`.
    var appicon_87: RswiftResources.ImageResource { .init(name: "appicon_87", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_1`.
    var bazhuawan_1: RswiftResources.ImageResource { .init(name: "bazhuawan_1", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_10`.
    var bazhuawan_10: RswiftResources.ImageResource { .init(name: "bazhuawan_10", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_11`.
    var bazhuawan_11: RswiftResources.ImageResource { .init(name: "bazhuawan_11", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_12`.
    var bazhuawan_12: RswiftResources.ImageResource { .init(name: "bazhuawan_12", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_13`.
    var bazhuawan_13: RswiftResources.ImageResource { .init(name: "bazhuawan_13", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_14`.
    var bazhuawan_14: RswiftResources.ImageResource { .init(name: "bazhuawan_14", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_15`.
    var bazhuawan_15: RswiftResources.ImageResource { .init(name: "bazhuawan_15", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_16`.
    var bazhuawan_16: RswiftResources.ImageResource { .init(name: "bazhuawan_16", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_17`.
    var bazhuawan_17: RswiftResources.ImageResource { .init(name: "bazhuawan_17", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_18`.
    var bazhuawan_18: RswiftResources.ImageResource { .init(name: "bazhuawan_18", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_19`.
    var bazhuawan_19: RswiftResources.ImageResource { .init(name: "bazhuawan_19", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_2`.
    var bazhuawan_2: RswiftResources.ImageResource { .init(name: "bazhuawan_2", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_20`.
    var bazhuawan_20: RswiftResources.ImageResource { .init(name: "bazhuawan_20", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_3`.
    var bazhuawan_3: RswiftResources.ImageResource { .init(name: "bazhuawan_3", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_4`.
    var bazhuawan_4: RswiftResources.ImageResource { .init(name: "bazhuawan_4", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_5`.
    var bazhuawan_5: RswiftResources.ImageResource { .init(name: "bazhuawan_5", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_6`.
    var bazhuawan_6: RswiftResources.ImageResource { .init(name: "bazhuawan_6", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_7`.
    var bazhuawan_7: RswiftResources.ImageResource { .init(name: "bazhuawan_7", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_8`.
    var bazhuawan_8: RswiftResources.ImageResource { .init(name: "bazhuawan_8", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_9`.
    var bazhuawan_9: RswiftResources.ImageResource { .init(name: "bazhuawan_9", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_empty`.
    var bazhuawan_empty: RswiftResources.ImageResource { .init(name: "bazhuawan_empty", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_error`.
    var bazhuawan_error: RswiftResources.ImageResource { .init(name: "bazhuawan_error", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `bazhuawan_icon`.
    var bazhuawan_icon: RswiftResources.ImageResource { .init(name: "bazhuawan_icon", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `book_normal`.
    var book_normal: RswiftResources.ImageResource { .init(name: "book_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `book_selected`.
    var book_selected: RswiftResources.ImageResource { .init(name: "book_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `camra_beauty`.
    var camra_beauty: RswiftResources.ImageResource { .init(name: "camra_beauty", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `camra_beauty_close`.
    var camra_beauty_close: RswiftResources.ImageResource { .init(name: "camra_beauty_close", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `camra_preview`.
    var camra_preview: RswiftResources.ImageResource { .init(name: "camra_preview", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `chrome`.
    var chrome: RswiftResources.ImageResource { .init(name: "chrome", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `close_preview`.
    var close_preview: RswiftResources.ImageResource { .init(name: "close_preview", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `colorpicker`.
    var colorpicker: RswiftResources.ImageResource { .init(name: "colorpicker", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `confetti`.
    var confetti: RswiftResources.ImageResource { .init(name: "confetti", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `cubs_logo`.
    var cubs_logo: RswiftResources.ImageResource { .init(name: "cubs_logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `danger`.
    var danger: RswiftResources.ImageResource { .init(name: "danger", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `diamond`.
    var diamond: RswiftResources.ImageResource { .init(name: "diamond", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `duke_logo`.
    var duke_logo: RswiftResources.ImageResource { .init(name: "duke_logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fave_heart`.
    var fave_heart: RswiftResources.ImageResource { .init(name: "fave_heart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fave_like`.
    var fave_like: RswiftResources.ImageResource { .init(name: "fave_like", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fave_smile`.
    var fave_smile: RswiftResources.ImageResource { .init(name: "fave_smile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fave_star`.
    var fave_star: RswiftResources.ImageResource { .init(name: "fave_star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `firefox`.
    var firefox: RswiftResources.ImageResource { .init(name: "firefox", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `flowers.jpg`.
    var flowersJpg: RswiftResources.ImageResource { .init(name: "flowers.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g1_back`.
    var g1_back: RswiftResources.ImageResource { .init(name: "g1_back", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g1_up`.
    var g1_up: RswiftResources.ImageResource { .init(name: "g1_up", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g2_back`.
    var g2_back: RswiftResources.ImageResource { .init(name: "g2_back", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g2_up`.
    var g2_up: RswiftResources.ImageResource { .init(name: "g2_up", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g3_back`.
    var g3_back: RswiftResources.ImageResource { .init(name: "g3_back", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g3_up`.
    var g3_up: RswiftResources.ImageResource { .init(name: "g3_up", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g4_back`.
    var g4_back: RswiftResources.ImageResource { .init(name: "g4_back", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g4_up`.
    var g4_up: RswiftResources.ImageResource { .init(name: "g4_up", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g5_back`.
    var g5_back: RswiftResources.ImageResource { .init(name: "g5_back", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g5_up`.
    var g5_up: RswiftResources.ImageResource { .init(name: "g5_up", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g6_back`.
    var g6_back: RswiftResources.ImageResource { .init(name: "g6_back", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g6_up`.
    var g6_up: RswiftResources.ImageResource { .init(name: "g6_up", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g7_back`.
    var g7_back: RswiftResources.ImageResource { .init(name: "g7_back", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g7_up`.
    var g7_up: RswiftResources.ImageResource { .init(name: "g7_up", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g8_back.jpg`.
    var g8_backJpg: RswiftResources.ImageResource { .init(name: "g8_back.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g8_up.jpg`.
    var g8_upJpg: RswiftResources.ImageResource { .init(name: "g8_up.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g9_back.jpg`.
    var g9_backJpg: RswiftResources.ImageResource { .init(name: "g9_back.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `g9_up.jpg`.
    var g9_upJpg: RswiftResources.ImageResource { .init(name: "g9_up.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `guaguale.jpg`.
    var guagualeJpg: RswiftResources.ImageResource { .init(name: "guaguale.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `heart-empty`.
    var heartEmpty: RswiftResources.ImageResource { .init(name: "heart-empty", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `heart-full`.
    var heartFull: RswiftResources.ImageResource { .init(name: "heart-full", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `heart-half`.
    var heartHalf: RswiftResources.ImageResource { .init(name: "heart-half", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `home_normal`.
    var home_normal: RswiftResources.ImageResource { .init(name: "home_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `home_selected`.
    var home_selected: RswiftResources.ImageResource { .init(name: "home_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon`.
    var icon: RswiftResources.ImageResource { .init(name: "icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cat`.
    var icon_cat: RswiftResources.ImageResource { .init(name: "icon_cat", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_close`.
    var icon_close: RswiftResources.ImageResource { .init(name: "icon_close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_footprint`.
    var icon_footprint: RswiftResources.ImageResource { .init(name: "icon_footprint", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_home`.
    var icon_home: RswiftResources.ImageResource { .init(name: "icon_home", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_menu`.
    var icon_menu: RswiftResources.ImageResource { .init(name: "icon_menu", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_search`.
    var icon_search: RswiftResources.ImageResource { .init(name: "icon_search", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `indicator1`.
    var indicator1: RswiftResources.ImageResource { .init(name: "indicator1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `indicator2`.
    var indicator2: RswiftResources.ImageResource { .init(name: "indicator2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `info`.
    var info: RswiftResources.ImageResource { .init(name: "info", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iphone_5s`.
    var iphone_5s: RswiftResources.ImageResource { .init(name: "iphone_5s", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launchimage`.
    var launchimage: RswiftResources.ImageResource { .init(name: "launchimage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `love`.
    var love: RswiftResources.ImageResource { .init(name: "love", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `mine_normal`.
    var mine_normal: RswiftResources.ImageResource { .init(name: "mine_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mine_selected`.
    var mine_selected: RswiftResources.ImageResource { .init(name: "mine_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `more`.
    var more: RswiftResources.ImageResource { .init(name: "more", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `nearby-btn`.
    var nearbyBtn: RswiftResources.ImageResource { .init(name: "nearby-btn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `notifications-btn`.
    var notificationsBtn: RswiftResources.ImageResource { .init(name: "notifications-btn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `plusBtn_bg`.
    var plusBtn_bg: RswiftResources.ImageResource { .init(name: "plusBtn_bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `plusBtn_normal`.
    var plusBtn_normal: RswiftResources.ImageResource { .init(name: "plusBtn_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `plusBtn_selected`.
    var plusBtn_selected: RswiftResources.ImageResource { .init(name: "plusBtn_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `radar_marker`.
    var radar_marker: RswiftResources.ImageResource { .init(name: "radar_marker", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `right_chevron`.
    var right_chevron: RswiftResources.ImageResource { .init(name: "right_chevron", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `safari`.
    var safari: RswiftResources.ImageResource { .init(name: "safari", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings-btn`.
    var settingsBtn: RswiftResources.ImageResource { .init(name: "settings-btn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_btn`.
    var settings_btn: RswiftResources.ImageResource { .init(name: "settings_btn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_1`.
    var slanted_1: RswiftResources.ImageResource { .init(name: "slanted_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_10`.
    var slanted_10: RswiftResources.ImageResource { .init(name: "slanted_10", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_12`.
    var slanted_12: RswiftResources.ImageResource { .init(name: "slanted_12", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_13`.
    var slanted_13: RswiftResources.ImageResource { .init(name: "slanted_13", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_14`.
    var slanted_14: RswiftResources.ImageResource { .init(name: "slanted_14", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_2`.
    var slanted_2: RswiftResources.ImageResource { .init(name: "slanted_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_3`.
    var slanted_3: RswiftResources.ImageResource { .init(name: "slanted_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_4`.
    var slanted_4: RswiftResources.ImageResource { .init(name: "slanted_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_5`.
    var slanted_5: RswiftResources.ImageResource { .init(name: "slanted_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_6`.
    var slanted_6: RswiftResources.ImageResource { .init(name: "slanted_6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_7`.
    var slanted_7: RswiftResources.ImageResource { .init(name: "slanted_7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `slanted_9`.
    var slanted_9: RswiftResources.ImageResource { .init(name: "slanted_9", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `star`.
    var star: RswiftResources.ImageResource { .init(name: "star", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `study_normal`.
    var study_normal: RswiftResources.ImageResource { .init(name: "study_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `study_selected`.
    var study_selected: RswiftResources.ImageResource { .init(name: "study_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `success`.
    var success: RswiftResources.ImageResource { .init(name: "success", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `supreme`.
    var supreme: RswiftResources.ImageResource { .init(name: "supreme", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `tab_bar_icon`.
    var tab_bar_icon: RswiftResources.ImageResource { .init(name: "tab_bar_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `transparentBG`.
    var transparentBG: RswiftResources.ImageResource { .init(name: "transparentBG", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `triangle`.
    var triangle: RswiftResources.ImageResource { .init(name: "triangle", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `unc_logo`.
    var unc_logo: RswiftResources.ImageResource { .init(name: "unc_logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `上一个标记点`.
    var 上一个标记点: RswiftResources.ImageResource { .init(name: "上一个标记点", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `下一个标记点`.
    var 下一个标记点: RswiftResources.ImageResource { .init(name: "下一个标记点", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `二Icon-60`.
    var 二Icon60: RswiftResources.ImageResource { .init(name: "二Icon-60", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-76`.
    var 二Icon76: RswiftResources.ImageResource { .init(name: "二Icon-76", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-83.5`.
    var 二Icon835: RswiftResources.ImageResource { .init(name: "二Icon-83.5", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Notification`.
    var 二IconNotification: RswiftResources.ImageResource { .init(name: "二Icon-Notification", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Notification@2x-1`.
    var 二IconNotification2x1: RswiftResources.ImageResource { .init(name: "二Icon-Notification@2x-1", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Notification@2x-2`.
    var 二IconNotification2x2: RswiftResources.ImageResource { .init(name: "二Icon-Notification@2x-2", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Small`.
    var 二IconSmall: RswiftResources.ImageResource { .init(name: "二Icon-Small", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Small-1`.
    var 二IconSmall1: RswiftResources.ImageResource { .init(name: "二Icon-Small-1", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Small-40`.
    var 二IconSmall40: RswiftResources.ImageResource { .init(name: "二Icon-Small-40", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Small-40@2x-1`.
    var 二IconSmall402x1: RswiftResources.ImageResource { .init(name: "二Icon-Small-40@2x-1", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二Icon-Small@2x-1`.
    var 二IconSmall2x1: RswiftResources.ImageResource { .init(name: "二Icon-Small@2x-1", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `二icon`.
    var 二icon: RswiftResources.ImageResource { .init(name: "二icon", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `做笔记_保存笔记`.
    var 做笔记_保存笔记: RswiftResources.ImageResource { .init(name: "做笔记_保存笔记", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_展开`.
    var 做笔记_展开: RswiftResources.ImageResource { .init(name: "做笔记_展开", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_打字_已选中`.
    var 做笔记_打字_已选中: RswiftResources.ImageResource { .init(name: "做笔记_打字_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_打字_未选中`.
    var 做笔记_打字_未选中: RswiftResources.ImageResource { .init(name: "做笔记_打字_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_收起`.
    var 做笔记_收起: RswiftResources.ImageResource { .init(name: "做笔记_收起", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔_已选中`.
    var 做笔记_画笔_已选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔_未选中`.
    var 做笔记_画笔_未选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_1_已选中`.
    var 做笔记_画笔粗细_1_已选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_1_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_1_未选中`.
    var 做笔记_画笔粗细_1_未选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_1_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_2_已选中`.
    var 做笔记_画笔粗细_2_已选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_2_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_2_未选中`.
    var 做笔记_画笔粗细_2_未选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_2_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_3_已选中`.
    var 做笔记_画笔粗细_3_已选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_3_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_3_未选中`.
    var 做笔记_画笔粗细_3_未选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_3_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_4_已选中`.
    var 做笔记_画笔粗细_4_已选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_4_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_画笔粗细_4_未选中`.
    var 做笔记_画笔粗细_4_未选中: RswiftResources.ImageResource { .init(name: "做笔记_画笔粗细_4_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_返回听课`.
    var 做笔记_返回听课: RswiftResources.ImageResource { .init(name: "做笔记_返回听课", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_选中颜色`.
    var 做笔记_选中颜色: RswiftResources.ImageResource { .init(name: "做笔记_选中颜色", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_选择字号_已选中`.
    var 做笔记_选择字号_已选中: RswiftResources.ImageResource { .init(name: "做笔记_选择字号_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_选择字号_未选中`.
    var 做笔记_选择字号_未选中: RswiftResources.ImageResource { .init(name: "做笔记_选择字号_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_逐条删除_已选中`.
    var 做笔记_逐条删除_已选中: RswiftResources.ImageResource { .init(name: "做笔记_逐条删除_已选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `做笔记_逐条删除_未选中`.
    var 做笔记_逐条删除_未选中: RswiftResources.ImageResource { .init(name: "做笔记_逐条删除_未选中", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_倍速0.5`.
    var 播放器_倍速05: RswiftResources.ImageResource { .init(name: "播放器_倍速0.5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_倍速1.0`.
    var 播放器_倍速10: RswiftResources.ImageResource { .init(name: "播放器_倍速1.0", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_倍速1.2`.
    var 播放器_倍速12: RswiftResources.ImageResource { .init(name: "播放器_倍速1.2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_倍速1.5`.
    var 播放器_倍速15: RswiftResources.ImageResource { .init(name: "播放器_倍速1.5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_倍速2.0`.
    var 播放器_倍速20: RswiftResources.ImageResource { .init(name: "播放器_倍速2.0", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_播放`.
    var 播放器_播放: RswiftResources.ImageResource { .init(name: "播放器_播放", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_暂停`.
    var 播放器_暂停: RswiftResources.ImageResource { .init(name: "播放器_暂停", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_返回`.
    var 播放器_返回: RswiftResources.ImageResource { .init(name: "播放器_返回", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `播放器_进度球`.
    var 播放器_进度球: RswiftResources.ImageResource { .init(name: "播放器_进度球", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `标记_划重点`.
    var 标记_划重点: RswiftResources.ImageResource { .init(name: "标记_划重点", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `标记_有点难`.
    var 标记_有点难: RswiftResources.ImageResource { .init(name: "标记_有点难", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `标记_标记点`.
    var 标记_标记点: RswiftResources.ImageResource { .init(name: "标记_标记点", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `标记_重点`.
    var 标记_重点: RswiftResources.ImageResource { .init(name: "标记_重点", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `标记_难点`.
    var 标记_难点: RswiftResources.ImageResource { .init(name: "标记_难点", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `画板_删除笔记`.
    var 画板_删除笔记: RswiftResources.ImageResource { .init(name: "画板_删除笔记", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `看笔记_全部笔记`.
    var 看笔记_全部笔记: RswiftResources.ImageResource { .init(name: "看笔记_全部笔记", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `看笔记_收起我的笔记`.
    var 看笔记_收起我的笔记: RswiftResources.ImageResource { .init(name: "看笔记_收起我的笔记", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `看笔记_编辑笔记`.
    var 看笔记_编辑笔记: RswiftResources.ImageResource { .init(name: "看笔记_编辑笔记", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `看笔记_返回听课`.
    var 看笔记_返回听课: RswiftResources.ImageResource { .init(name: "看笔记_返回听课", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `看笔记_退出编辑`.
    var 看笔记_退出编辑: RswiftResources.ImageResource { .init(name: "看笔记_退出编辑", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `知识点_关闭`.
    var 知识点_关闭: RswiftResources.ImageResource { .init(name: "知识点_关闭", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `知识点_箭头`.
    var 知识点_箭头: RswiftResources.ImageResource { .init(name: "知识点_箭头", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `知识点_跳转`.
    var 知识点_跳转: RswiftResources.ImageResource { .init(name: "知识点_跳转", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `笔记_做笔记`.
    var 笔记_做笔记: RswiftResources.ImageResource { .init(name: "笔记_做笔记", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `笔记_看笔记`.
    var 笔记_看笔记: RswiftResources.ImageResource { .init(name: "笔记_看笔记", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `词汇通关_默认视频`.
    var 词汇通关_默认视频: RswiftResources.ImageResource { .init(name: "词汇通关_默认视频", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 1 properties.
  struct entitlements {
    let comAppleSecurityApplicationGroups = comAppleSecurityApplicationGroups()
    struct comAppleSecurityApplicationGroups {
      let groupSparkMmkv: String = "group.spark.mmkv"
    }
  }

  /// This `_R.font` struct is generated, and contains static references to 11 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `OpenSans`.
    var openSans: RswiftResources.FontResource { .init(name: "OpenSans", bundle: bundle, filename: "OpenSans-Regular.ttf") }

    /// Font `OpenSans-Bold`.
    var openSansBold: RswiftResources.FontResource { .init(name: "OpenSans-Bold", bundle: bundle, filename: "OpenSans-Bold.ttf") }

    /// Font `OpenSans-BoldItalic`.
    var openSansBoldItalic: RswiftResources.FontResource { .init(name: "OpenSans-BoldItalic", bundle: bundle, filename: "OpenSans-BoldItalic.ttf") }

    /// Font `OpenSans-Extrabold`.
    var openSansExtrabold: RswiftResources.FontResource { .init(name: "OpenSans-Extrabold", bundle: bundle, filename: "OpenSans-ExtraBold.ttf") }

    /// Font `OpenSans-ExtraboldItalic`.
    var openSansExtraboldItalic: RswiftResources.FontResource { .init(name: "OpenSans-ExtraboldItalic", bundle: bundle, filename: "OpenSans-ExtraBoldItalic.ttf") }

    /// Font `OpenSans-Italic`.
    var openSansItalic: RswiftResources.FontResource { .init(name: "OpenSans-Italic", bundle: bundle, filename: "OpenSans-Italic.ttf") }

    /// Font `OpenSans-Light`.
    var openSansLight: RswiftResources.FontResource { .init(name: "OpenSans-Light", bundle: bundle, filename: "OpenSans-Light.ttf") }

    /// Font `OpenSans-Semibold`.
    var openSansSemibold: RswiftResources.FontResource { .init(name: "OpenSans-Semibold", bundle: bundle, filename: "OpenSans-Semibold.ttf") }

    /// Font `OpenSans-SemiboldItalic`.
    var openSansSemiboldItalic: RswiftResources.FontResource { .init(name: "OpenSans-SemiboldItalic", bundle: bundle, filename: "OpenSans-SemiboldItalic.ttf") }

    /// Font `OpenSansLight-Italic`.
    var openSansLightItalic: RswiftResources.FontResource { .init(name: "OpenSansLight-Italic", bundle: bundle, filename: "OpenSans-LightItalic.ttf") }

    /// Font `Shape`.
    var shape: RswiftResources.FontResource { .init(name: "Shape", bundle: bundle, filename: "shape.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [openSans, openSansBold, openSansBoldItalic, openSansExtrabold, openSansExtraboldItalic, openSansItalic, openSansLight, openSansSemibold, openSansSemiboldItalic, openSansLightItalic, shape].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 124 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `CLCamera.bundle`.
    var clCameraBundle: RswiftResources.FileResource { .init(name: "CLCamera", pathExtension: "bundle", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `DanielWu.jpg`.
    var danielWuJpg: RswiftResources.FileResource { .init(name: "DanielWu", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `DanielWuFace.png`.
    var danielWuFacePng: RswiftResources.FileResource { .init(name: "DanielWuFace", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Dilraba.gif`.
    var dilrabaGif: RswiftResources.FileResource { .init(name: "Dilraba", pathExtension: "gif", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Gem.gif`.
    var gemGif: RswiftResources.FileResource { .init(name: "Gem", pathExtension: "gif", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl1.jpg`.
    var girl1Jpg: RswiftResources.FileResource { .init(name: "Girl1", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl2.jpg`.
    var girl2Jpg: RswiftResources.FileResource { .init(name: "Girl2", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl3.jpg`.
    var girl3Jpg: RswiftResources.FileResource { .init(name: "Girl3", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl4.jpg`.
    var girl4Jpg: RswiftResources.FileResource { .init(name: "Girl4", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl5.jpg`.
    var girl5Jpg: RswiftResources.FileResource { .init(name: "Girl5", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl6.jpg`.
    var girl6Jpg: RswiftResources.FileResource { .init(name: "Girl6", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl7.jpg`.
    var girl7Jpg: RswiftResources.FileResource { .init(name: "Girl7", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Girl8.jpg`.
    var girl8Jpg: RswiftResources.FileResource { .init(name: "Girl8", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Kobe.jpg`.
    var kobeJpg: RswiftResources.FileResource { .init(name: "Kobe", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `LICENSE.txt`.
    var licenseTxt: RswiftResources.FileResource { .init(name: "LICENSE", pathExtension: "txt", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Bold.ttf`.
    var openSansBoldTtf: RswiftResources.FileResource { .init(name: "OpenSans-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-BoldItalic.ttf`.
    var openSansBoldItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-BoldItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-ExtraBold.ttf`.
    var openSansExtraBoldTtf: RswiftResources.FileResource { .init(name: "OpenSans-ExtraBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-ExtraBoldItalic.ttf`.
    var openSansExtraBoldItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-ExtraBoldItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Italic.ttf`.
    var openSansItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-Italic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Light.ttf`.
    var openSansLightTtf: RswiftResources.FileResource { .init(name: "OpenSans-Light", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-LightItalic.ttf`.
    var openSansLightItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-LightItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Regular.ttf`.
    var openSansRegularTtf: RswiftResources.FileResource { .init(name: "OpenSans-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Semibold.ttf`.
    var openSansSemiboldTtf: RswiftResources.FileResource { .init(name: "OpenSans-Semibold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-SemiboldItalic.ttf`.
    var openSansSemiboldItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-SemiboldItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_1024.png`.
    var appicon_1024Png: RswiftResources.FileResource { .init(name: "appicon_1024", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_120.png`.
    var appicon_120Png: RswiftResources.FileResource { .init(name: "appicon_120", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_152.png`.
    var appicon_152Png: RswiftResources.FileResource { .init(name: "appicon_152", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_167.png`.
    var appicon_167Png: RswiftResources.FileResource { .init(name: "appicon_167", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_180.png`.
    var appicon_180Png: RswiftResources.FileResource { .init(name: "appicon_180", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_20.png`.
    var appicon_20Png: RswiftResources.FileResource { .init(name: "appicon_20", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_29.png`.
    var appicon_29Png: RswiftResources.FileResource { .init(name: "appicon_29", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_40.png`.
    var appicon_40Png: RswiftResources.FileResource { .init(name: "appicon_40", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_58.png`.
    var appicon_58Png: RswiftResources.FileResource { .init(name: "appicon_58", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_60.png`.
    var appicon_60Png: RswiftResources.FileResource { .init(name: "appicon_60", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_76.png`.
    var appicon_76Png: RswiftResources.FileResource { .init(name: "appicon_76", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_80.png`.
    var appicon_80Png: RswiftResources.FileResource { .init(name: "appicon_80", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `appicon_87.png`.
    var appicon_87Png: RswiftResources.FileResource { .init(name: "appicon_87", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_1.png`.
    var bazhuawan_1Png: RswiftResources.FileResource { .init(name: "bazhuawan_1", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_10.png`.
    var bazhuawan_10Png: RswiftResources.FileResource { .init(name: "bazhuawan_10", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_11.png`.
    var bazhuawan_11Png: RswiftResources.FileResource { .init(name: "bazhuawan_11", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_12.png`.
    var bazhuawan_12Png: RswiftResources.FileResource { .init(name: "bazhuawan_12", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_13.png`.
    var bazhuawan_13Png: RswiftResources.FileResource { .init(name: "bazhuawan_13", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_14.png`.
    var bazhuawan_14Png: RswiftResources.FileResource { .init(name: "bazhuawan_14", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_15.png`.
    var bazhuawan_15Png: RswiftResources.FileResource { .init(name: "bazhuawan_15", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_16.png`.
    var bazhuawan_16Png: RswiftResources.FileResource { .init(name: "bazhuawan_16", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_17.png`.
    var bazhuawan_17Png: RswiftResources.FileResource { .init(name: "bazhuawan_17", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_18.png`.
    var bazhuawan_18Png: RswiftResources.FileResource { .init(name: "bazhuawan_18", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_19.png`.
    var bazhuawan_19Png: RswiftResources.FileResource { .init(name: "bazhuawan_19", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_2.png`.
    var bazhuawan_2Png: RswiftResources.FileResource { .init(name: "bazhuawan_2", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_20.png`.
    var bazhuawan_20Png: RswiftResources.FileResource { .init(name: "bazhuawan_20", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_3.png`.
    var bazhuawan_3Png: RswiftResources.FileResource { .init(name: "bazhuawan_3", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_4.png`.
    var bazhuawan_4Png: RswiftResources.FileResource { .init(name: "bazhuawan_4", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_5.png`.
    var bazhuawan_5Png: RswiftResources.FileResource { .init(name: "bazhuawan_5", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_6.png`.
    var bazhuawan_6Png: RswiftResources.FileResource { .init(name: "bazhuawan_6", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_7.png`.
    var bazhuawan_7Png: RswiftResources.FileResource { .init(name: "bazhuawan_7", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_8.png`.
    var bazhuawan_8Png: RswiftResources.FileResource { .init(name: "bazhuawan_8", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_9.png`.
    var bazhuawan_9Png: RswiftResources.FileResource { .init(name: "bazhuawan_9", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_empty.png`.
    var bazhuawan_emptyPng: RswiftResources.FileResource { .init(name: "bazhuawan_empty", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_error.png`.
    var bazhuawan_errorPng: RswiftResources.FileResource { .init(name: "bazhuawan_error", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `bazhuawan_icon.png`.
    var bazhuawan_iconPng: RswiftResources.FileResource { .init(name: "bazhuawan_icon", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `camra_beauty@2x.png`.
    var camra_beauty2xPng: RswiftResources.FileResource { .init(name: "camra_beauty@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `camra_beauty@3x.png`.
    var camra_beauty3xPng: RswiftResources.FileResource { .init(name: "camra_beauty@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `camra_beauty_close@2x.png`.
    var camra_beauty_close2xPng: RswiftResources.FileResource { .init(name: "camra_beauty_close@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `camra_beauty_close@3x.png`.
    var camra_beauty_close3xPng: RswiftResources.FileResource { .init(name: "camra_beauty_close@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `camra_preview@2x.png`.
    var camra_preview2xPng: RswiftResources.FileResource { .init(name: "camra_preview@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `camra_preview@3x.png`.
    var camra_preview3xPng: RswiftResources.FileResource { .init(name: "camra_preview@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `close_preview@2x.png`.
    var close_preview2xPng: RswiftResources.FileResource { .init(name: "close_preview@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `close_preview@3x.png`.
    var close_preview3xPng: RswiftResources.FileResource { .init(name: "close_preview@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `colorpicker.png`.
    var colorpickerPng: RswiftResources.FileResource { .init(name: "colorpicker", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `confetti.png`.
    var confettiPng: RswiftResources.FileResource { .init(name: "confetti", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `covers.plist`.
    var coversPlist: RswiftResources.FileResource { .init(name: "covers", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `data.tsv`.
    var dataTsv: RswiftResources.FileResource { .init(name: "data", pathExtension: "tsv", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `diamond.png`.
    var diamondPng: RswiftResources.FileResource { .init(name: "diamond", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `flowers.jpg`.
    var flowersJpg: RswiftResources.FileResource { .init(name: "flowers", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g1_back.png`.
    var g1_backPng: RswiftResources.FileResource { .init(name: "g1_back", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g1_up.png`.
    var g1_upPng: RswiftResources.FileResource { .init(name: "g1_up", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g2_back.png`.
    var g2_backPng: RswiftResources.FileResource { .init(name: "g2_back", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g2_up.png`.
    var g2_upPng: RswiftResources.FileResource { .init(name: "g2_up", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g3_back.png`.
    var g3_backPng: RswiftResources.FileResource { .init(name: "g3_back", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g3_up.png`.
    var g3_upPng: RswiftResources.FileResource { .init(name: "g3_up", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g4_back.png`.
    var g4_backPng: RswiftResources.FileResource { .init(name: "g4_back", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g4_up.png`.
    var g4_upPng: RswiftResources.FileResource { .init(name: "g4_up", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g5_back.png`.
    var g5_backPng: RswiftResources.FileResource { .init(name: "g5_back", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g5_up.png`.
    var g5_upPng: RswiftResources.FileResource { .init(name: "g5_up", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g6_back.png`.
    var g6_backPng: RswiftResources.FileResource { .init(name: "g6_back", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g6_up.png`.
    var g6_upPng: RswiftResources.FileResource { .init(name: "g6_up", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g7_back.png`.
    var g7_backPng: RswiftResources.FileResource { .init(name: "g7_back", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g7_up.png`.
    var g7_upPng: RswiftResources.FileResource { .init(name: "g7_up", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g8_back.jpg`.
    var g8_backJpg: RswiftResources.FileResource { .init(name: "g8_back", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g8_up.jpg`.
    var g8_upJpg: RswiftResources.FileResource { .init(name: "g8_up", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g9_back.jpg`.
    var g9_backJpg: RswiftResources.FileResource { .init(name: "g9_back", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `g9_up.jpg`.
    var g9_upJpg: RswiftResources.FileResource { .init(name: "g9_up", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `guaguale.jpg`.
    var guagualeJpg: RswiftResources.FileResource { .init(name: "guaguale", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_cat@2x.png`.
    var icon_cat2xPng: RswiftResources.FileResource { .init(name: "icon_cat@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_footprint@2x.png`.
    var icon_footprint2xPng: RswiftResources.FileResource { .init(name: "icon_footprint@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `love.png`.
    var lovePng: RswiftResources.FileResource { .init(name: "love", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `radar_marker@3x.png`.
    var radar_marker3xPng: RswiftResources.FileResource { .init(name: "radar_marker@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `shape.ttf`.
    var shapeTtf: RswiftResources.FileResource { .init(name: "shape", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `shapeList.plist`.
    var shapeListPlist: RswiftResources.FileResource { .init(name: "shapeList", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `star.png`.
    var starPng: RswiftResources.FileResource { .init(name: "star", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `supreme.png`.
    var supremePng: RswiftResources.FileResource { .init(name: "supreme", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `transparentBG.png`.
    var transparentBGPng: RswiftResources.FileResource { .init(name: "transparentBG", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `triangle.png`.
    var trianglePng: RswiftResources.FileResource { .init(name: "triangle", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `yaorenmao.mov`.
    var yaorenmaoMov: RswiftResources.FileResource { .init(name: "yaorenmao", pathExtension: "mov", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-60@2x.png`.
    var 二Icon602xPng: RswiftResources.FileResource { .init(name: "二Icon-60@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-60@3x.png`.
    var 二Icon603xPng: RswiftResources.FileResource { .init(name: "二Icon-60@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-76.png`.
    var 二Icon76Png: RswiftResources.FileResource { .init(name: "二Icon-76", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-76@2x.png`.
    var 二Icon762xPng: RswiftResources.FileResource { .init(name: "二Icon-76@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-83.5@2x.png`.
    var 二Icon8352xPng: RswiftResources.FileResource { .init(name: "二Icon-83.5@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Notification@2x-1.png`.
    var 二IconNotification2x1Png: RswiftResources.FileResource { .init(name: "二Icon-Notification@2x-1", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Notification@2x-2.png`.
    var 二IconNotification2x2Png: RswiftResources.FileResource { .init(name: "二Icon-Notification@2x-2", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Notification@2x.png`.
    var 二IconNotification2xPng: RswiftResources.FileResource { .init(name: "二Icon-Notification@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Notification@3x.png`.
    var 二IconNotification3xPng: RswiftResources.FileResource { .init(name: "二Icon-Notification@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small-1.png`.
    var 二IconSmall1Png: RswiftResources.FileResource { .init(name: "二Icon-Small-1", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small-40.png`.
    var 二IconSmall40Png: RswiftResources.FileResource { .init(name: "二Icon-Small-40", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small-40@2x-1.png`.
    var 二IconSmall402x1Png: RswiftResources.FileResource { .init(name: "二Icon-Small-40@2x-1", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small-40@2x.png`.
    var 二IconSmall402xPng: RswiftResources.FileResource { .init(name: "二Icon-Small-40@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small-40@3x.png`.
    var 二IconSmall403xPng: RswiftResources.FileResource { .init(name: "二Icon-Small-40@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small@2x-1.png`.
    var 二IconSmall2x1Png: RswiftResources.FileResource { .init(name: "二Icon-Small@2x-1", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small@2x.png`.
    var 二IconSmall2xPng: RswiftResources.FileResource { .init(name: "二Icon-Small@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二Icon-Small@3x.png`.
    var 二IconSmall3xPng: RswiftResources.FileResource { .init(name: "二Icon-Small@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `二icon.png`.
    var 二iconPng: RswiftResources.FileResource { .init(name: "二icon", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `测试视频文件.mp4`.
    var 测试视频文件Mp4: RswiftResources.FileResource { .init(name: "测试视频文件", pathExtension: "mp4", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 42 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `AnotherBarChartViewController`.
    var anotherBarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "AnotherBarChartViewController", bundle: bundle) }

    /// Nib `AutolayoutView`.
    var autolayoutView: RswiftResources.NibReference<AutolayoutView> { .init(name: "AutolayoutView", bundle: bundle) }

    /// Nib `BarChartViewController`.
    var barChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "BarChartViewController", bundle: bundle) }

    /// Nib `BubbleChartViewController`.
    var bubbleChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "BubbleChartViewController", bundle: bundle) }

    /// Nib `CandleStickChartViewController`.
    var candleStickChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CandleStickChartViewController", bundle: bundle) }

    /// Nib `CheckmarkView`.
    var checkmarkView: RswiftResources.NibReference<CheckmarkView> { .init(name: "CheckmarkView", bundle: bundle) }

    /// Nib `ColoredLineChartViewController`.
    var coloredLineChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ColoredLineChartViewController", bundle: bundle) }

    /// Nib `CombinedChartViewController`.
    var combinedChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CombinedChartViewController", bundle: bundle) }

    /// Nib `CountdownLabelVC`.
    var countdownLabelVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CountdownLabelVC", bundle: bundle) }

    /// Nib `CubicLineChartViewController`.
    var cubicLineChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CubicLineChartViewController", bundle: bundle) }

    /// Nib `DemoListViewController`.
    var demoListViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "DemoListViewController", bundle: bundle) }

    /// Nib `GradientLoadingBarVC`.
    var gradientLoadingBarVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "GradientLoadingBarVC", bundle: bundle) }

    /// Nib `HalfPieChartViewController`.
    var halfPieChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "HalfPieChartViewController", bundle: bundle) }

    /// Nib `HorizontalBarChartViewController`.
    var horizontalBarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "HorizontalBarChartViewController", bundle: bundle) }

    /// Nib `LaunchScreen`.
    var launchScreen: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LaunchScreen", bundle: bundle) }

    /// Nib `LineChart1ViewController`.
    var lineChart1ViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LineChart1ViewController", bundle: bundle) }

    /// Nib `LineChart2ViewController`.
    var lineChart2ViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LineChart2ViewController", bundle: bundle) }

    /// Nib `LineChartFilledViewController`.
    var lineChartFilledViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LineChartFilledViewController", bundle: bundle) }

    /// Nib `LineChartTimeViewController`.
    var lineChartTimeViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LineChartTimeViewController", bundle: bundle) }

    /// Nib `ListCell2`.
    var listCell2: RswiftResources.NibReference<ListCell2> { .init(name: "ListCell2", bundle: bundle) }

    /// Nib `LTMorphingLabelVC`.
    var ltMorphingLabelVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LTMorphingLabelVC", bundle: bundle) }

    /// Nib `MarqueeTouchCharacterVC`.
    var marqueeTouchCharacterVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MarqueeTouchCharacterVC", bundle: bundle) }

    /// Nib `MarqueeVC`.
    var marqueeVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MarqueeVC", bundle: bundle) }

    /// Nib `MultipleBarChartViewController`.
    var multipleBarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MultipleBarChartViewController", bundle: bundle) }

    /// Nib `MultipleLinesChartViewController`.
    var multipleLinesChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MultipleLinesChartViewController", bundle: bundle) }

    /// Nib `NegativeStackedBarChartViewController`.
    var negativeStackedBarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "NegativeStackedBarChartViewController", bundle: bundle) }

    /// Nib `NumberMorphVC`.
    var numberMorphVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "NumberMorphVC", bundle: bundle) }

    /// Nib `PieChartViewController`.
    var pieChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PieChartViewController", bundle: bundle) }

    /// Nib `PiePolylineChartViewController`.
    var piePolylineChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PiePolylineChartViewController", bundle: bundle) }

    /// Nib `PopTipVC`.
    var popTipVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PopTipVC", bundle: bundle) }

    /// Nib `PositiveNegativeBarChartViewController`.
    var positiveNegativeBarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PositiveNegativeBarChartViewController", bundle: bundle) }

    /// Nib `PulsatorVC`.
    var pulsatorVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PulsatorVC", bundle: bundle) }

    /// Nib `RadarChartViewController`.
    var radarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "RadarChartViewController", bundle: bundle) }

    /// Nib `RadarMarkerView`.
    var radarMarkerView: RswiftResources.NibReference<RadarMarkerView> { .init(name: "RadarMarkerView", bundle: bundle) }

    /// Nib `RealmDemosViewController`.
    var realmDemosViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "RealmDemosViewController", bundle: bundle) }

    /// Nib `ScatterChartViewController`.
    var scatterChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ScatterChartViewController", bundle: bundle) }

    /// Nib `SinusBarChartViewController`.
    var sinusBarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SinusBarChartViewController", bundle: bundle) }

    /// Nib `SlantedSettingVC`.
    var slantedSettingVC: RswiftResources.NibReference<SlantedSetting> { .init(name: "SlantedSettingVC", bundle: bundle) }

    /// Nib `SlotCell`.
    var slotCell: RswiftResources.NibReference<SlotCell> { .init(name: "SlotCell", bundle: bundle) }

    /// Nib `SparkViewController`.
    var sparkViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SparkViewController", bundle: bundle) }

    /// Nib `StackedBarChartViewController`.
    var stackedBarChartViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "StackedBarChartViewController", bundle: bundle) }

    /// Nib `TitleView`.
    var titleView: RswiftResources.NibReference<TitleView> { .init(name: "TitleView", bundle: bundle) }

    func validate() throws {
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "checkmark.seal") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'checkmark.seal' is used in nib 'CheckmarkView', but couldn't be loaded.") } }
      if UIKit.UIImage(named: "cat", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'cat' is used in nib 'ListCell2', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iphone_5s", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iphone_5s' is used in nib 'PulsatorVC', but couldn't be loaded.") }
      if UIKit.UIImage(named: "radar_marker.png", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'radar_marker.png' is used in nib 'RadarMarkerView', but couldn't be loaded.") }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var languageExample: languageExample { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func languageExample(bundle: Foundation.Bundle) -> languageExample {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.languageExample.validate()
      try self.main.validate()
    }


    /// Storyboard `LanguageExample`.
    struct languageExample: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "LanguageExample"

      var languageExampleViewController: RswiftResources.StoryboardViewControllerIdentifier<LanguageExampleViewController> { .init(identifier: "LanguageExampleViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if languageExampleViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'languageExampleViewController' could not be loaded from storyboard 'LanguageExample' as 'LanguageExampleViewController'.") }
      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ViewController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}